// AUTO-GENERATED by scripts/gen-data.mjs from the origin site's rendered markup.
// Content is verbatim; do not hand-edit — regenerate instead.
/* eslint-disable */

export type Listing = {
  href: string;
  image: string;
  alt: string;
  price: string;
  meta: string;
  address: string;
  neighborhood: string;
  logoSrc?: string;
};

export type ListingRow = {
  heading: string;
  seeAll: string;
  seeAllHref: string;
  listings: Listing[];
};

export const LISTING_ROWS: ListingRow[] = [
  {
    "heading": "Homes in Williamsburg",
    "seeAll": "See all homes →",
    "seeAllHref": "/neighborhoods/brooklyn/williamsburg/listings",
    "listings": [
      {
        "href": "/properties/3090412",
        "image": "/sites/www-findrealestate-com-715c1bfa/root-8a5edab2/content/169de036-5df3-4f91-8a4f-aa4c24cbd214-a6f9c9.jpg",
        "alt": "75 South 9th Street, Apt Building, Brooklyn, NY 11249",
        "price": "$4,500,000",
        "meta": "For Sale · 8 beds · 4 baths",
        "address": "75 South 9th Street, Apt Building, Brooklyn, NY 11249",
        "neighborhood": "Williamsburg"
      },
      {
        "href": "/properties/3090182",
        "image": "/sites/www-findrealestate-com-715c1bfa/root-8a5edab2/content/52610178-25b5-4de3-bbeb-0922e489abff-b3f5a6.jpg",
        "alt": "339 Bedford Avenue, Apt 30, Brooklyn, NY 11211",
        "price": "$4,200/mo",
        "meta": "For Rent · 2 beds · 1 bath",
        "address": "339 Bedford Avenue, Apt 30, Brooklyn, NY 11211",
        "neighborhood": "Williamsburg"
      },
      {
        "href": "/properties/3090162",
        "image": "/sites/www-findrealestate-com-715c1bfa/root-8a5edab2/content/3489ea7c-63be-41ba-839f-17b7425ce8af-0b5c26.jpg",
        "alt": "373 South 4th Street, Apt 10, Brooklyn, NY 11211",
        "price": "$5,650/mo",
        "meta": "For Rent · 3 beds · 1 bath",
        "address": "373 South 4th Street, Apt 10, Brooklyn, NY 11211",
        "neighborhood": "Williamsburg"
      },
      {
        "href": "/properties/3091055",
        "image": "/sites/www-findrealestate-com-715c1bfa/root-8a5edab2/content/108621734_IMG_0546-aaedd7.png",
        "alt": "256 North 9th Street, Apt 2B, Brooklyn, NY 11211",
        "price": "$8,500/mo",
        "meta": "For Rent · 2 beds · 2 baths",
        "address": "256 North 9th Street, Apt 2B, Brooklyn, NY 11211",
        "neighborhood": "Williamsburg",
        "logoSrc": "/sites/www-findrealestate-com-715c1bfa/root-8a5edab2/content/REBNY_logo-3e86df.png"
      }
    ]
  },
  {
    "heading": "Homes in Astoria",
    "seeAll": "See all homes →",
    "seeAllHref": "/neighborhoods/queens/astoria/listings",
    "listings": [
      {
        "href": "/properties/3091248",
        "image": "/sites/www-findrealestate-com-715c1bfa/root-8a5edab2/content/KEY426511781_f0488276-3be0-40cd-9839-7345b51471e-18bd53.jpeg",
        "alt": "33-64 21st Street, Apt 6-C, Astoria, NY 11106",
        "price": "$519,999",
        "meta": "For Sale · 2 beds · 1 bath",
        "address": "33-64 21st Street, Apt 6-C, Astoria, NY 11106",
        "neighborhood": "Astoria",
        "logoSrc": "/sites/www-findrealestate-com-715c1bfa/root-8a5edab2/content/OneKeyMLS_logo-e702df.png"
      },
      {
        "href": "/properties/3091247",
        "image": "/sites/www-findrealestate-com-715c1bfa/root-8a5edab2/content/KEY427302939_5f65b3cf-7d25-4448-bbf2-c681f805927-07558f.jpeg",
        "alt": "3514 30th Avenue, Astoria, NY 11103",
        "price": "$1,900/mo",
        "meta": "For Rent · 1 bed · 1 bath",
        "address": "3514 30th Avenue, Astoria, NY 11103",
        "neighborhood": "Astoria",
        "logoSrc": "/sites/www-findrealestate-com-715c1bfa/root-8a5edab2/content/OneKeyMLS_logo-e702df.png"
      },
      {
        "href": "/properties/3090824",
        "image": "/sites/www-findrealestate-com-715c1bfa/root-8a5edab2/content/KEY427297114_ba55c9bc-5504-45c5-a861-b814b19ae52-0c9b95.jpeg",
        "alt": "2540 Shore Boulevard, Apt 20-N, Astoria, NY 11102",
        "price": "$575,000",
        "meta": "For Sale · 1 bed · 1 bath",
        "address": "2540 Shore Boulevard, Apt 20-N, Astoria, NY 11102",
        "neighborhood": "Astoria",
        "logoSrc": "/sites/www-findrealestate-com-715c1bfa/root-8a5edab2/content/OneKeyMLS_logo-e702df.png"
      },
      {
        "href": "/properties/3090731",
        "image": "/sites/www-findrealestate-com-715c1bfa/root-8a5edab2/content/KEY427297087_8c104f29-7b1a-460b-bae4-a1263a6d55e-477e3e.jpeg",
        "alt": "1833 27th Avenue, Astoria, NY 11102",
        "price": "$2,100,000",
        "meta": "For Sale · 6 beds · 3 baths",
        "address": "1833 27th Avenue, Astoria, NY 11102",
        "neighborhood": "Astoria",
        "logoSrc": "/sites/www-findrealestate-com-715c1bfa/root-8a5edab2/content/OneKeyMLS_logo-e702df.png"
      }
    ]
  },
  {
    "heading": "Homes in Chelsea",
    "seeAll": "See all homes →",
    "seeAllHref": "/neighborhoods/manhattan/chelsea/listings",
    "listings": [
      {
        "href": "/properties/3091067",
        "image": "/sites/www-findrealestate-com-715c1bfa/root-8a5edab2/content/115033550_DSC_8986_1-e01e5f.jpg",
        "alt": "405 West 23rd Street, Apt 7J, New York, NY 10011",
        "price": "$590,000",
        "meta": "For Sale · Studio · 1 bath",
        "address": "405 West 23rd Street, Apt 7J, New York, NY 10011",
        "neighborhood": "Chelsea",
        "logoSrc": "/sites/www-findrealestate-com-715c1bfa/root-8a5edab2/content/REBNY_logo-3e86df.png"
      },
      {
        "href": "/properties/3091038",
        "image": "/sites/www-findrealestate-com-715c1bfa/root-8a5edab2/content/01a0fd2f-5ae7-78e2-acac-e65cf3396a4a-a9973f.jpg",
        "alt": "100 West 15th Street, Apt 5F, New York, NY 10011",
        "price": "$525,000",
        "meta": "For Sale · Studio · 1 bath",
        "address": "100 West 15th Street, Apt 5F, New York, NY 10011",
        "neighborhood": "Chelsea",
        "logoSrc": "/sites/www-findrealestate-com-715c1bfa/root-8a5edab2/content/REBNY_logo-3e86df.png"
      },
      {
        "href": "/properties/2937476",
        "image": "/sites/www-findrealestate-com-715c1bfa/root-8a5edab2/content/01941d8c-2ca5-447c-8900-d245f9aaea5a-514852.jpg",
        "alt": "315 Seventh Avenue, Apt 8-D, New York, NY 10001",
        "price": "$4,000/mo",
        "meta": "For Rent · Studio · 1 bath",
        "address": "315 Seventh Avenue, Apt 8-D, New York, NY 10001",
        "neighborhood": "Chelsea"
      },
      {
        "href": "/properties/3088779",
        "image": "/sites/www-findrealestate-com-715c1bfa/root-8a5edab2/content/115033550_DSC_8986_1-e01e5f.jpg",
        "alt": "256 West 21st Street, Apt G1, New York, NY 10011",
        "price": "$1,250,000",
        "meta": "For Sale · 1 bed · 1 bath",
        "address": "256 West 21st Street, Apt G1, New York, NY 10011",
        "neighborhood": "Chelsea",
        "logoSrc": "/sites/www-findrealestate-com-715c1bfa/root-8a5edab2/content/REBNY_logo-3e86df.png"
      }
    ]
  }
];

export const DISCLAIMER_LOGOS = [
  {
    "src": "/sites/www-findrealestate-com-715c1bfa/root-8a5edab2/content/REBNY_logo-3e86df.png",
    "alt": "IDX: REBNY"
  },
  {
    "src": "/sites/www-findrealestate-com-715c1bfa/root-8a5edab2/content/OneKeyMLS_logo-e702df.png",
    "alt": "IDX: OneKey"
  }
];

export const DISCLAIMER_PARAGRAPHS: string[] = [
  "Listing information for certain New York City properties is provided courtesy of the Real Estate Board of New York's Residential Listing Service (the \"RLS\"). This information is not verified for authenticity or accuracy, is not guaranteed, and may not reflect all real estate activity in the market. ©2026 The Real Estate Board of New York, Inc., All rights reserved.",
  "The data relating to real estate for sale on this website also comes in part from the IDX Program of OneKey® MLS. Information Copyright 2026, OneKey® MLS. All data is deemed reliable but is not guaranteed accurate.",
  "All listing information provided here is exclusively for consumers' personal, non-commercial use, and may not be used for any purpose other than to identify prospective properties consumers may be interested in purchasing. Some IDX listings may have been excluded from this website."
];

export type Testimonial = { quote: string; author: string };

export const TESTIMONIALS: Testimonial[] = [
  {
    "quote": "\"Michael was a great realtor. Such a hard worker, dedicated to helping us find the perfect neighborhood, price point and home. He's a workaholic so he was available morning, noon and night. Tireless and dedicated. Would recommend him 100%!\"",
    "author": "Bernadette Hogan"
  },
  {
    "quote": "\"Shirin was truly a blessing to work with. She helped us find our perfect condo in a great area. She was patient and very understanding. I would recommend working with her if you are in need of someone who will go out of their way to make sure you find the home of your dreams. She is honest and has a pure heart.\"",
    "author": "Tyleen"
  },
  {
    "quote": "\"Working with Mathew was an absolute pleasure, and I highly recommend him to any serious homebuyer—especially first-time buyers like myself who may feel overwhelmed by the process. From the start, Mathew’s problem-solving skills stood out. Thank you, Mathew, for making this happen—we are truly happy in our new home!\"",
    "author": "Johanna Nieto"
  },
  {
    "quote": "\"Shirin was an invaluable resource, consultant, and general guide through the home-buying process from the initial search to closing. She immediately understood what we were looking for in a home and helped tailor our search in the right direction. Shirin was quickly responsive and proactive in pushing the agenda forward through all stages with a steady, reassuring hand.\"",
    "author": "mattmpowers"
  },
  {
    "quote": "\"After 12 years in NYC, I have had my best broker experience by far with Fay Blau. Fay helped me find a beautiful apartment on the Upper West Side that fit my needs like a glove. As an Upper West Side local, she knows the neighborhood like the back of her hand. She was an excellent communicator throughout the entire process.\"",
    "author": "Giavridis Theodore"
  }
];

export type Service = { label: string; text: string; image: string };

export const SERVICES: Service[] = [
  {
    "label": "Buy",
    "text": "Buy smarter with expert agents backed by mortgage, legal, and appraisal pros—dialed in to get you the best deal, fast. We’ve done this over 10,000 times, and we know what wins.",
    "image": "/sites/www-findrealestate-com-715c1bfa/root-8a5edab2/images/buy.fed72bc8.jpg"
  },
  {
    "label": "Sell",
    "text": "Sell fast, sell high. Your listing gets pro staging, strategic pricing, constant open houses, and agents who never stop working until the right buyer signs.",
    "image": "/sites/www-findrealestate-com-715c1bfa/root-8a5edab2/images/sell.90b8e66b.jpg"
  },
  {
    "label": "Rent",
    "text": "Access hidden rentals before they hit the market through agents who know every landlord in town. With decades of NYC experience, we unlock the best deals you won’t find online.",
    "image": "/sites/www-findrealestate-com-715c1bfa/root-8a5edab2/images/rent.6736c732.jpg"
  }
];

export const SERVICES_BRIEF = "Our certified agents guide you through every stage of real estate with expert knowledge and reliable support.";

export type Feature = { title: string; text: string; image: string };

export const FEATURES: Feature[] = [
  {
    "title": "Mortgage Services",
    "text": "Helping you secure your dream home with flexible mortgage options.",
    "image": "/sites/www-findrealestate-com-715c1bfa/root-8a5edab2/images/mortgage-services.e92904b1.jpg"
  },
  {
    "title": "Property Management",
    "text": "Let us handle the details so you can enjoy the rewards.",
    "image": "/sites/www-findrealestate-com-715c1bfa/root-8a5edab2/images/property-management.7a9cbb34.jpg"
  },
  {
    "title": "Construction and Real Estate Development",
    "text": "Guiding you through the intricacies of building and developing properties with expert insight and support.",
    "image": "/sites/www-findrealestate-com-715c1bfa/root-8a5edab2/images/development.0de63e1b.jpg"
  }
];

export type Post = {
  href: string;
  title: string;
  date: string;
  excerpt: string;
  image: string;
  alt: string;
};

export const POSTS: Post[] = [
  {
    "href": "/blog/what-it-really-costs-to-live-in-harry-styles-neighborhood",
    "title": "FIND Real Estate Featured in Redfin: What It Really Costs to Live in Harry Styles’ Neighborhood",
    "date": "2026-09-02",
    "excerpt": "A look at the housing prices, everyday expenses, and lifestyle costs in Harry Styles’ neighborhood.",
    "image": "/sites/www-findrealestate-com-715c1bfa/root-8a5edab2/content/Untitled_design_2026_09_02_T035929_341_6ca6e73a0-a9e69c.png",
    "alt": "FIND Real Estate Featured in Redfin: What It Really Costs to Live in Harry Styles’ Neighborhood"
  },
  {
    "href": "/blog/Q1-2026-NYC-Market-Report",
    "title": "Q1 2026 NYC Market Report",
    "date": "2026-04-13",
    "excerpt": "Q1 2026 saw strong rental demand, active sales, and shifting pricing across NYC. Here’s what it means heading into the spring market.",
    "image": "/sites/www-findrealestate-com-715c1bfa/root-8a5edab2/content/nyc_604e40fa02-47bacf.png",
    "alt": "Q1 2026 NYC Market Report"
  },
  {
    "href": "/blog/philly-real-estate-winter-chill-spring-opportunity",
    "title": "Philly Real Estate: A Winter Chill or a Spring Opportunity?",
    "date": "2026-04-01",
    "excerpt": "Record-low listings and steady price growth define a unique February for the Philadelphia Metro.",
    "image": "/sites/www-findrealestate-com-715c1bfa/root-8a5edab2/content/jonathan_gong_tl3jdt_Z_u_YM_unsplash_5f055e7e75-322c52.jpg",
    "alt": "Philly Real Estate: A Winter Chill or a Spring Opportunity?"
  }
];
