import fs from "node:fs";
import path from "node:path";
import { htmlToJsx } from "./port-dom.mjs";

const RES = path.join(
  process.cwd(),
  "docs/research/www-findrealestate-com-715c1bfa/root-8a5edab2",
);
const OUT = path.join(
  process.cwd(),
  "src/components/sites/www-findrealestate-com-715c1bfa/root-8a5edab2/shared/icons.tsx",
);

function firstSvg(html) {
  const i = html.indexOf("<svg");
  if (i === -1) return null;
  // find matching close
  let depth = 0;
  const re = /<(\/?)svg\b[^>]*?(\/?)>/g;
  re.lastIndex = i;
  let m;
  while ((m = re.exec(html))) {
    if (m[1] === "/") {
      depth--;
      if (depth === 0) return html.slice(i, m.index + m[0].length);
    } else if (!m[2]) {
      depth++;
    }
  }
  return null;
}

const header = fs.readFileSync(path.join(RES, "chrome/header.html"), "utf8");
const hero = fs.readFileSync(path.join(RES, "sections/00-hero_root__N0Loz.html"), "utf8");
const services = fs.readFileSync(path.join(RES, "sections/07-services_root__Ch_WM.html"), "utf8");

const wordmark = firstSvg(header); // FIND logo (4 letters)
// 24x24 icons are distinguishable by their path data.
const svgs24 = [...(header + hero).matchAll(/<svg[^>]*viewBox="0 0 24 24"[\s\S]*?<\/svg>/g)].map((m) => m[0]);
const arrow = svgs24.find((s) => s.includes("20.78 12.531")) ?? null;
const chevron = svgs24.find((s) => s.includes("17.566 9.431")) ?? null;
// The oversized slanted arrow inside `.services_item-more` (also used by the
// Services/Outro round buttons).
const svgsServices = [...services.matchAll(/<svg[^>]*viewBox="0 0 24 24"[\s\S]*?<\/svg>/g)].map((m) => m[0]);
const arrowSlant = svgsServices.find((s) => s.includes("M3.315 10.996")) ?? null;

// The big outlined wordmark used by the hero (same viewBox as the CSS mask).
const heroLogo = hero.slice(hero.indexOf('class="hero_logo'), hero.indexOf("hero_smoke"));
const outlined = firstSvg(heroLogo);

function svgToComponent(name, svg, propsDoc) {
  if (!svg) throw new Error("missing svg for " + name);
  let jsx = htmlToJsx(svg)
    .split("\n")
    .map((l) => "    " + l)
    .join("\n");
  // hoist the root svg attrs so callers can size it
  jsx = jsx
    .replace(/^ {4}<svg /, "    <svg {...props} ")
    // The origin leaves GSAP's stroke-draw endpoints inline (a zero-length dash,
    // i.e. an invisible stroke). Drop them so the wordmark renders fully drawn.
    .replace(/\s*strokeDashoffset: "[^"]*",?/g, "")
    .replace(/\s*strokeDasharray: "[^"]*",?/g, "")
    .replace(/style=\{\{\s*\}\}/g, "");
  return `export function ${name}(props: SVGProps<SVGSVGElement>) {\n  return (\n${jsx}\n  );\n}`;
}

const out = `// AUTO-GENERATED by scripts/gen-icons.mjs from the origin site's inline SVG.
// Do not edit by hand — regenerate instead.
import { type SVGProps } from "react";

${svgToComponent("LogoIcon", wordmark)}

${svgToComponent("ArrowRightIcon", arrow)}

${svgToComponent("ChevronDownIcon", chevron)}

${svgToComponent("ArrowSlantIcon", arrowSlant)}

${svgToComponent("OutlinedWordmark", outlined)}
`;

fs.mkdirSync(path.dirname(OUT), { recursive: true });
fs.writeFileSync(OUT, out);
console.log("wrote", OUT, out.length);
